id = "scenic"
name = "Scenic"
version = "0.1.0"
schema_version = 1
authors = ["Scenic tree-sitter contributors"]
description = "Scenic language support with Tree-sitter syntax highlighting."
repository = "https://github.com/Maciej4/scenic-zed"
snippets = ["./snippets/scenic.json"]

[grammars.scenic]
repository = "https://github.com/Maciej4/tree-sitter-scenic"
rev = "295233d104b1fdaedc9f660e37e2b485f43b466e"
